[theme]
primaryColor = "#FF5733"        # Accent color for buttons, badges
backgroundColor = "#F2F2F2"     # App background
secondaryBackgroundColor = "#FFFFFF"  # Container/card background
textColor = "#111111"            # Main text
font = "Raleway"              # Font style
